# 1. numpy 객체

In [10]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [11]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [12]:
np.array([1, 2, 3, 4]).reshape((2, 2))

array([[1, 2],
       [3, 4]])

In [13]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# 배열의 색인
array = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
array[0]

array([1, 2, 3])

In [16]:
array[1]

array([4, 5, 6])

In [17]:
array[0, :2]

array([1, 2])

In [18]:
array[0, 2]

3

In [19]:
array.ndim # 차원

2

In [20]:
array.shape # 각 차원의 길이

(2, 3)

In [21]:
array.dtype # 데이터 타입

dtype('int32')

In [22]:
array.sum() # 합계
array.min() # 최솟값
array.max() # 최대값
array.mean() # 평균값
array.std() # 표준편차

1.707825127659933

In [31]:
# 함수
nums = np.array([1, 2, 2, 3])

In [32]:
set(nums)

{1, 2, 3}

In [33]:
np.unique(nums)

array([1, 2, 3])

In [34]:
len(np.unique(nums))

3

In [35]:
len(nums)

4

In [36]:
np.arange(3, 8, 2)
# np.arange(start=5, stop=20, step=5)
# array([5, 10, 15])

array([3, 5, 7])

In [38]:
np.where(nums == 2,"ok", "no")

array(['no', 'ok', 'ok', 'no'], dtype='<U2')

# 2. Pandas 객체-Series

In [39]:
import pandas as pd
ser = pd.Series([1, 2, 3])
ser

0    1
1    2
2    3
dtype: int64

In [40]:
ser.values

array([1, 2, 3], dtype=int64)

In [41]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [42]:
pd.Series([1, 2, 3, 3, 4])

0    1
1    2
2    3
3    3
4    4
dtype: int64

In [43]:
pd.Series([1, 2, 3], index = ["a", "b", "c"])

a    1
b    2
c    3
dtype: int64

In [44]:
ser = pd.Series([1, 2, 3, 3, 4])

In [45]:
ser.sum()
ser.min()
ser.max()
ser.mean()
ser.std()

1.140175425099138

In [46]:
ser.skew() # 왜도

-0.404796008910937

In [47]:
ser.kurt() # 첨도

-0.17751479289941052

In [48]:
ser.unique() # 고유값

array([1, 2, 3, 4], dtype=int64)

In [49]:
ser.idxmax() # 최대값의 위치

4

In [51]:
ser.idxmin() # 최솟값의 위치

0

In [50]:
ser.isin([1, 2]) # 포함 여부 검사

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [52]:
ser.isin([1, 2]).sum()

2

# 2. Pandas 객체-DataFrame

In [62]:
df = pd.DataFrame({"aa": [1, 2, 3], 
                   "bb": [2, 3, 4]})
df

aa  bb
0   1   2
1   2   3
2   3   4

In [54]:
df.aa

0    1
1    2
2    3
Name: aa, dtype: int64

In [55]:
df["aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [56]:
df["aa"][:2]

0    1
1    2
Name: aa, dtype: int64

In [57]:
df.iloc[:, 0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [58]:
df.loc[:, "aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [59]:
df.iloc[:2, :] # 정수 기반 인덱싱

aa  bb
0   1   2
1   2   3

In [60]:
df.iloc[:, 0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [61]:
df.loc[:, "aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

# 데이터 요약

In [63]:
# crosstab 빈도표
pd.crosstab(df['aa'], df['bb'])

bb  2  3  4
aa         
1   1  0  0
2   0  1  0
3   0  0  1

In [64]:
# groupby
# 특정 변수를 기준으로 요약 연산
df.groupby('aa')['bb'].sum()

aa
1    2
2    3
3    4
Name: bb, dtype: int64